import "@/styles/globals.css";

import { Inter } from "next/font/google";
import React from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AuthProvider } from "@/lib/providers/Auth";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.variable}`}>
				<AuthProvider api="rest">{children}</AuthProvider>
				<SpeedInsights />
			</body>
		</html>
	);
}
